version: '3.8'

services:
  django:
    container_name: lectureleague-django
    build:
      context: ./core/
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./core/db.sqlite3:/home/app/web/db.sqlite3:rw
      - static:/home/app/web/staticfiles:rw
      - media:/home/app/web/mediafiles:rw
    ports:
      - "8000:8000"
    networks:
      - lectureleague-network
    env_file:
      - ./core/.env.development

  proxy:
    container_name: lectureleague-proxy
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - static:/home/proxy/staticfiles:rw
      - media:/home/proxy/mediafiles:rw
    ports:
      - "8080:80"
    depends_on:
      - django
    networks:
      - lectureleague-network

  mailserver:
    container_name: lectureleague-mailserver
    image: mailhog/mailhog
    ports:
      - "8025:8025"

networks:
  lectureleague-network:
    name: lectureleague-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1

volumes:
  database:
    name: database
    driver: local
  static:
    name: static
    driver: local
  media:
    name: media
    driver: local
